#!/bin/zsh

# TODO: Make better update indication for this script

# Function used for "update" subcommand of zflex
function update {
	local repo

	if (( $# )); then
		for repo in $ZFLEX_STORAGE/**/.git(/); do
			print -P "%F{005}Zflex: %F{003}Updating: %F{004}${repo:h:t}%f"
			git -C "${repo:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print -Pu2 "%F{005}Zflex: %F{001}Couldn't update: ${repo:h:t}%f" &
		done
		wait
	else
		for repo in $ZFLEX_STORAGE/**/$@/.git(/); do
			print -P "%F{005}Zflex: %F{003}Updating: %F{004}${repo:h:t}%f"
			git -C "${repo:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print -Pu2 "%F{005}Zflex: %F{001}Couldn't update: ${repo:t}%f" &
		done
		wait
	fi
}

update "$@"
